// Code generated by "stringer -type=AddressingMode -output addressing_modes.gen.go"; DO NOT EDIT.

package cpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IMP-0]
	_ = x[IMM-1]
	_ = x[ZP-2]
	_ = x[ZPX-3]
	_ = x[ZPY-4]
	_ = x[IZX-5]
	_ = x[IZY-6]
	_ = x[ABS-7]
	_ = x[ABX-8]
	_ = x[ABY-9]
	_ = x[IND-10]
	_ = x[REL-11]
}

const _AddressingMode_name = "IMPIMMZPZPXZPYIZXIZYABSABXABYINDREL"

var _AddressingMode_index = [...]uint8{0, 3, 6, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35}

func (i AddressingMode) String() string {
	if i < 0 || i >= AddressingMode(len(_AddressingMode_index)-1) {
		return "AddressingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressingMode_name[_AddressingMode_index[i]:_AddressingMode_index[i+1]]
}
